Fix TypeError
When we have both the protocols and QObject as parent classes, we get:

TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

I'm not sure how to solve this well, but removing the explicit inheritance of the protocols does fix it.